name: Python Package using Conda (amd64 Compatible)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Define size variable
      run: |
        echo "Setting size variable..."
        echo "SIZE=1024" >> $GITHUB_ENV  # Example size value

    - name: Lint with flake8
      run: |
        # Lint and fail on errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat warnings as non-failure
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Install pytest
        pip install pytest
        # Run tests
        pytest

    - name: Compatibility for amd64
      run: |
        echo "Ensuring compatibility for amd64 architecture..."
        uname -m
