name: Python Package using Conda (amd64 Compatible)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check architecture
        run: uname -m
      

      - name: Setup Python
        uses: actions
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Define size variable
        run: |
          echo "Setting size variable..."
            size = value = 0o123
            size_filter = size.maxint
          echo "SIZE=1024" >> $GITHUB_ENV 

      - name: Lint with flake8
        run: |
           flake8 . --count --select=F821 --show-source --statistics
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          # Install pytest
          pip install pytest
          # Run tests
          pytest

      - name: Compatibility for amd64
        run: |
          echo "Ensuring compatibility for amd64 architecture..."
          uname -m
